version: '3'

services:
  mysql:
    image: 5g_log_mysql:0.2  # 使用您指定的镜像
    container_name: test2-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1235
    ports:
      - "3309:3306"  # 映射宿主机端口 3009 到容器的 3306 端口
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      grafana-net:
        ipv4_address: "192.168.11.10"

  grafana:
    image: grafana/grafana-enterprise
    container_name: test2-grafana
    ports:
      - "3003:3000"  # 映射宿主机端口 3002 到容器的 3000 端口
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - mysql
    networks:
      grafana-net:
        ipv4_address: "192.168.11.11"
volumes:
  mysql_data:

networks:
  grafana-net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.11.0/24"

