version: '3'

services:
  mysql:
    image: kongrong25/5g_log_mysql:1.0
    container_name: my_grafana_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1235
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      grafana-net:
        ipv4_address: "192.168.11.10"

  grafana:
    image: kongrong25/5g_log_grafana:1.2
    container_name: my_grafana
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - mysql
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      grafana-net:
        ipv4_address: "192.168.11.11"
volumes:
  mysql_data:
  grafana_data:
networks:
  grafana-net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.11.0/24"

